"""Media generator dispatch — the binary-asset counterpart to domain text recipes.

The executor hands a media node a dict of inputs (text as `str`, upstream media
as file paths) and this module returns the generated bytes.
"""

from __future__ import annotations

from pathlib import Path

from . import audio, images, video


class MediaRenderError(ValueError):
    pass


def render_media(node, inputs: dict[str, object]) -> bytes:
    recipe = node.operation.get("recipe")
    if recipe == "poster":
        return images.render_poster(str(inputs["title"]), str(inputs["product"]))
    if recipe == "cutout":
        return images.render_cutout(str(inputs["product"]))
    if recipe == "keyframe":
        return images.render_keyframe(
            str(inputs["plan"]), Path(inputs["cutout"]), int(node.operation.get("index", 1))
        )
    if recipe == "narration":
        return audio.render_narration(str(inputs["description"]))
    if recipe == "delivery":
        return video.render_delivery(
            poster=Path(inputs["poster"]),
            keyframes=[Path(inputs["k1"]), Path(inputs["k2"]), Path(inputs["k3"])],
            narration=Path(inputs["narration"]),
        )
    raise MediaRenderError(f"node {node.stable_key!r} has unknown media recipe {recipe!r}")
